byte_tracker_node:
  ros__parameters:
    input_topic: "detections_output"
    output_topic: "tracked_detections"
    image_topic: "image/image_raw"
    image_width: 0
    image_height: 0
    default_class_id: "target"
    min_score: 0.01

    track_thresh: 0.25
    track_buffer: 30
    match_thresh: 0.8
    mot20: false
    frame_rate: 30
